// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ficbatch/models/reading_progress.dart';
import 'package:ficbatch/models/work.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ReadingProgressAdapter());
    registerAdapter(WorkAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ReadingProgressAdapter());
    registerAdapter(WorkAdapter());
  }
}
